services:
  postgresql:
    image: postgres:17
    container_name: postgresql
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - app-network
    restart: on-failure

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: django
    container_name: django
    env_file: ./.env
    environment:
      FORTY_TWO_CLIENT_SECRET: ${FORTY_TWO_CLIENT_SECRET}
      FORTY_TWO_CLIENT_ID: ${FORTY_TWO_CLIENT_ID}
      MNEMONIC: ${MNEMONIC}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes: 
      - django-static:/app/static
      - django-media:/app/media
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - postgresql
      - ganache

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "4443:4443"
    volumes: 
      -  django-static:/app/static
      -  django-media:/app/media
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - django

  ganache:
    build:
      context: .
      dockerfile: ./docker/ganache/Dockerfile
    image: ganache
    container_name: ganache
    env_file: ./.env
    environment:
      MNEMONIC: ${MNEMONIC}
    volumes:
      - ganache_db:/ganache_db
    networks:
      - app-network
    restart: on-failure

volumes:
  postgresql: {}
  django-static: {}
  django-media: {}
  ganache_db: {}


networks:
  app-network:
    driver: bridge
    name: Transcendence_network
