from .login import login
from .logout import logout
from .register import register
from .isLogged import isLogged
from .userMe import userMe
from .userOther import userOther
from .favicon import favicon
from .index import index
from .tournaments import tournaments