services:
  postgresql:
    env_file:
      - ${ENV_FILE}
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  django:
    build:
      context: ..
      dockerfile: Dockerfile-django
    image: django
    container_name: django
    ports:
      - "443:443"
      - "80:80" # TODO
    env_file:
      - ${ENV_FILE}
    volumes: 
      - django:/django/static
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - postgresql

volumes:
  postgresql:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ../postgresql-data
      o: bind
  django:
    name: django
    driver: local
    driver_opts:
      type: none
      device: ../src
      o: bind

networks:
  app-network:
    driver: bridge
    name: app-network