services:
  postgresql:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - app-network

  django:
    build:
      context: ..
      dockerfile: ./docker/django/Dockerfile-django
    env_file:
      - ../.env
    image: django
    container_name: django
    volumes: 
      - django:/app
      - ganache_data:/app/blockchain_data  # Connect Django with Ganache
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - postgresql
      - ganache-hardhat

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ../.env
    volumes: 
      - django:/app
    networks:
      - app-network
    restart: on-failure
    depends_on:
      - django

  ganache-hardhat:
    build:
      context: ..
      dockerfile: ./docker/ganache/Dockerfile-ganache
    image: ganache-hardhat
    container_name: ganache-hardhat
    ports:
      - "7545:7545"
    volumes:
      - ganache_data:/app/blockchain_data  # Shared volume for Django
      - ganache_ref:/ganache_ref
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgresql:
    name: Transcendence_postgresql
    driver: local
    driver_opts:
      type: none
      device: ../postgresql-data
      o: bind
  django:
    name: Transcendence_django
    driver: local
    driver_opts:
      type: none
      device: ../django
      o: bind
  ganache_data:
    name: Transcendence_ganache
    driver: local
    driver_opts:
      type: none
      device: ../ganache-data
      o: bind
  ganache_ref:
    name: Transcendence_ganache_ref
    driver: local
    driver_opts:
      type: none
      device: ../ganache-ref
      o: bind

networks:
  app-network:
    driver: bridge
    name: Transcendence_network
