# Usa la imagen oficial de Python
FROM python:3.9-slim

# Instala las dependencias necesarias para Django
RUN pip install --no-cache-dir django

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Expone el puerto de Django (8000 por defecto)
EXPOSE 8000

# Comando para correr el servidor de Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]