# Generated by Django 3.2 on 2025-03-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='matchType',
            field=models.CharField(choices=[('local', 'local'), ('AI', 'AI'), ('online', 'online'), ('tournament-local', 'tournament-local'), ('tournament-online', 'tournament-online')], max_length=20),
        ),
    ]
