# Generated by Django 3.2 on 2025-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
    ]
