# Generated by Django 3.2 on 2025-03-09 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreLeft', models.IntegerField()),
                ('scoreRight', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('playerLeft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history_as_player_left', to=settings.AUTH_USER_MODEL)),
                ('playerRight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history_as_player_right', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
