# Generated by Django 3.2 on 2025-03-09 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0003_auto_20250309_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_pong_project_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
