# Generated by Django 3.2 on 2025-03-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0004_auto_20250324_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_activity',
        ),
    ]
