# Generated by Django 3.2 on 2025-03-26 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pong_project', '0005_auto_20250324_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
