# Usar una imagen base de Python 3
FROM python:3.9-buster

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

# Install dependencies
COPY ./docker/django/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

EXPOSE 8000

COPY ./docker/django/init.sh /usr/local/bin/init.sh
CMD ["bash", "/usr/local/bin/init.sh"]